
# This file is generated by opta, do not modify it manually.
provider "aws" {
  region              = "ap-south-1"
  allowed_account_ids = ["059709188241"]

  default_tags {
    tags = {
      environment_name = "adfg"
      region           = "ap-east-1"
      layer_name       = "sdfsdf"
      service_name       = "sdfsdf}"
    }
  }
}