# This file is generated by opta, do not modify it manually.
provider "aws" {
  region              = "ap-south-1"
  allowed_account_ids = ["609973658768"]

  default_tags {
    tags = {
      environment_name = "fdsafsadf"
      region           = "fdsafsadf"
      layer_name       = "fdsafsadf-fdsafsadf"
    }
  }
}